<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MonitorProfiles.Core\MonitorProfiles.Core.csproj" />
    <ProjectReference Include="..\MonitorProfiles.Storage\MonitorProfiles.Storage.csproj" />
    <ProjectReference Include="..\MonitorProfiles.Windows\MonitorProfiles.Windows.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

</Project>
